version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: koussay  
      MYSQL_DATABASE: koussay
    ports:
      - "3307:3306"
    
  backend-app:
    image: backend:latest  # Use the already built image
    container_name: backend-app
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      mysql:
        condition: service_healthy
    
  frontend-app:
    image: frontend-app:latest  # Use the already built image
    container_name: frontend-app
    restart: always
    ports:
      - "81:80"
